#!/bin/sh

# This tool is developed by Sebastiano Stipa, Politecnico di Milano, 2020 

cp -r 0.orig temp

rm -r processor*
rm -r 0*
rm -r 1*
rm -r 2*
rm -r 3*
rm -r 4*
rm -r 5*
rm -r 6*
rm -r dynamicCode
rm -r constant/polyMesh
rm -r VTK
rm -r postProcessing
rm -r log*

cp -r temp 0.orig

rm -r temp
